
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parsers.statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int AND = 20;
  public static final int SEMICOLON = 8;
  public static final int LESS_EQUAL = 28;
  public static final int OR = 21;
  public static final int RPAREN = 3;
  public static final int EQUAL = 29;
  public static final int CHAR = 16;
  public static final int NOT = 22;
  public static final int NOT_EQUAL = 30;
  public static final int GREATER_EQUAL = 27;
  public static final int GREATER = 25;
  public static final int TRUE = 18;
  public static final int LPAREN = 2;
  public static final int ID = 24;
  public static final int SUB = 5;
  public static final int STRING_LITERAL = 9;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int ADD = 4;
  public static final int CHAR_LITERAL = 12;
  public static final int MINUS = 31;
  public static final int FALSE = 19;
  public static final int PRINT = 32;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int INTEGER_LITERAL = 10;
  public static final int BOOL = 17;
  public static final int INTEGER = 14;
  public static final int LESS = 26;
  public static final int DOUBLE = 15;
  public static final int DOUBLE_LITERAL = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "ADD",
  "SUB",
  "DIV",
  "TIMES",
  "SEMICOLON",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "DOUBLE_LITERAL",
  "CHAR_LITERAL",
  "STRING",
  "INTEGER",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "ID",
  "GREATER",
  "LESS",
  "GREATER_EQUAL",
  "LESS_EQUAL",
  "EQUAL",
  "NOT_EQUAL",
  "MINUS",
  "PRINT"
  };
}

